### ISSUE TITLE
`R CMD check` fails to find `pkgapi` in R 4.0

### ISSUE THREAD

**Issue by devarops** [ropensci/mutant#13]
In [this workflow](https://github.com/ropensci/mutant/runs/694738484), `R CMD check` fails to find `pkgapi`

```
R CMD check 
* using R version 4.0.0 (2020-04-24)
##[error]Package suggested but not available: ‘pkgapi’
```

**Comment by devarops** [comment]
I'm adding this as an issue just to keep it visible.

**Comment by sckott** [comment]
not sure why that's the case

**Comment by devarops** [comment]
It's solved. I don't now how it fixed itself.
